/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.imagenFondo;

/**
 *
 * @author user
 */
public class mdiSFG25 extends javax.swing.JFrame {

    /**
     * Creates new form mdiSFG25
     */
    public mdiSFG25() {
        initComponents();
        this.setTitle("Sistema de Facturacion ");
        this.setExtendedState(this.MAXIMIZED_BOTH);
        panel.setBorder(new imagenFondo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mParametros = new javax.swing.JMenu();
        mpCategorias = new javax.swing.JMenuItem();
        mpProveedores = new javax.swing.JMenuItem();
        mpEmpleados = new javax.swing.JMenuItem();
        mpClientes = new javax.swing.JMenuItem();
        mpRoles = new javax.swing.JMenuItem();
        mpMetodosPago = new javax.swing.JMenuItem();
        mProcesos = new javax.swing.JMenu();
        mprInventario = new javax.swing.JMenuItem();
        mprFacturación = new javax.swing.JMenuItem();
        mprPermisos = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenu();
        mrCategorias = new javax.swing.JMenuItem();
        mrProveedores = new javax.swing.JMenuItem();
        mrEmpleados = new javax.swing.JMenuItem();
        mrClientes = new javax.swing.JMenuItem();
        meRoles = new javax.swing.JMenuItem();
        mrMetodosPago = new javax.swing.JMenuItem();
        mrUsuarios = new javax.swing.JMenuItem();
        mrInventario = new javax.swing.JMenuItem();
        mrFacturacion = new javax.swing.JMenuItem();
        mrPermisos = new javax.swing.JMenuItem();
        mSeguridad = new javax.swing.JMenu();
        msUsuarios = new javax.swing.JMenuItem();
        msPermisos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(0, 153, 153));
        jToolBar1.setRollover(true);

        panel.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        mParametros.setText("Parametros");
        mParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mParametrosActionPerformed(evt);
            }
        });

        mpCategorias.setText("Categorias");
        mpCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpCategoriasActionPerformed(evt);
            }
        });
        mParametros.add(mpCategorias);

        mpProveedores.setText("Proveedores");
        mParametros.add(mpProveedores);

        mpEmpleados.setText("Empleados");
        mParametros.add(mpEmpleados);

        mpClientes.setText("Clientes");
        mpClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpClientesActionPerformed(evt);
            }
        });
        mParametros.add(mpClientes);

        mpRoles.setText("Roles");
        mParametros.add(mpRoles);

        mpMetodosPago.setText("Metodos de Pago");
        mParametros.add(mpMetodosPago);

        jMenuBar1.add(mParametros);

        mProcesos.setText("Procesos");

        mprInventario.setText("Inventario");
        mProcesos.add(mprInventario);

        mprFacturación.setText("Facturación");
        mProcesos.add(mprFacturación);

        mprPermisos.setText("Permisos");
        mProcesos.add(mprPermisos);

        jMenuBar1.add(mProcesos);

        mReportes.setText("Reportes");

        mrCategorias.setText("Categorias");
        mReportes.add(mrCategorias);

        mrProveedores.setText("Proveedores");
        mReportes.add(mrProveedores);

        mrEmpleados.setText("Empleados");
        mReportes.add(mrEmpleados);

        mrClientes.setText("Clientes");
        mReportes.add(mrClientes);

        meRoles.setText("Roles");
        mReportes.add(meRoles);

        mrMetodosPago.setText("Metodos de Pago.");
        mReportes.add(mrMetodosPago);

        mrUsuarios.setText("Usuarios");
        mReportes.add(mrUsuarios);

        mrInventario.setText("Inventario.");
        mReportes.add(mrInventario);

        mrFacturacion.setText("Facturación");
        mReportes.add(mrFacturacion);

        mrPermisos.setText("Permisos");
        mReportes.add(mrPermisos);

        jMenuBar1.add(mReportes);

        mSeguridad.setText("Seguridad");

        msUsuarios.setText("Usuarios");
        mSeguridad.add(msUsuarios);

        msPermisos.setText("Permisos");
        mSeguridad.add(msPermisos);

        jMenuBar1.add(mSeguridad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpClientesActionPerformed

    private void mParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mParametrosActionPerformed

    private void mpCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpCategoriasActionPerformed
        jifrmCategorias vista = new jifrmCategorias();
        this.panel.add(vista);
        vista.show();
    }//GEN-LAST:event_mpCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiSFG25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiSFG25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiSFG25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiSFG25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiSFG25().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mParametros;
    private javax.swing.JMenu mProcesos;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenu mSeguridad;
    private javax.swing.JMenuItem meRoles;
    private javax.swing.JMenuItem mpCategorias;
    private javax.swing.JMenuItem mpClientes;
    private javax.swing.JMenuItem mpEmpleados;
    private javax.swing.JMenuItem mpMetodosPago;
    private javax.swing.JMenuItem mpProveedores;
    private javax.swing.JMenuItem mpRoles;
    private javax.swing.JMenuItem mprFacturación;
    private javax.swing.JMenuItem mprInventario;
    private javax.swing.JMenuItem mprPermisos;
    private javax.swing.JMenuItem mrCategorias;
    private javax.swing.JMenuItem mrClientes;
    private javax.swing.JMenuItem mrEmpleados;
    private javax.swing.JMenuItem mrFacturacion;
    private javax.swing.JMenuItem mrInventario;
    private javax.swing.JMenuItem mrMetodosPago;
    private javax.swing.JMenuItem mrPermisos;
    private javax.swing.JMenuItem mrProveedores;
    private javax.swing.JMenuItem mrUsuarios;
    private javax.swing.JMenuItem msPermisos;
    private javax.swing.JMenuItem msUsuarios;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
